Vagrant.configure("2") do |config|
  config.vm.box = "boxomatic/alpine-3.18"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.network "public_network", ip: "192.168.1.123"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "play-pyinit.yml"
  end
end
