---
- hosts: localhost
  connection: local
  gather_facts: false
  name: setup ansible dev tools
  tasks:
    - name: setting up ansible-lint, yamllint, black
      community.general.apk:
        name: ansible-lint,yamllint,black
        state: latest
      tags: [lintfmt]
    - name: create ansible-lint ignore file
      ansible.builtin.copy:
        content: ""
        dest: "{{ playbook_dir | dirname }}/.ansible-lint"
        force: false
        mode: '0644'
      tags: [lintfmt]
    - name: setting up ansible-lint ignore
      ansible.builtin.blockinfile:
        dest: "{{ playbook_dir | dirname }}/.ansible-lint"
        block: |
          skip_list:
              - "name[casing]"
      tags: [lintfmt]
    - name: check if yamlfmt is installed
      ansible.builtin.command:
        cmd: go version -m $GOBIN/yamlfmt
      register: package_status
      failed_when: false
      changed_when: false
      tags: [lintfmt]
    - name: install yamlfmt package
      ansible.builtin.command:
        cmd: go install -ldflags="-w -s" github.com/google/yamlfmt/cmd/yamlfmt@latest
      tags: [lintfmt]
      when: package_status.rc != 0
