---
- hosts: localhost
  gather_facts: true
  # https://stackoverflow.com/questions/71692791/is-it-possible-to-gather-only-specific-facts-in-ansible
  gather_subset:
    - "env"
    - "!all"
    - "!min"
  # vars:
    # path_go_bin: "{{lookup('env', 'PATH')}}:~/go/bin"
  tasks:
    - name: setting up local alpine machine
      block:
      - name: setting up go, gup and packages
        block:
        - name: install go
          community.general.apk:
            name: go
            state: latest
          tags:
            - go
        - name: check if gup is installed
          ansible.builtin.shell: command -v gup
          environment:
            PATH: "{{ ansible_env.HOME }}/go/bin:{{ ansible_env.PATH }}"
          register: gup_exists
          ignore_errors: true
          changed_when: false
          tags:
            - go
        - name: install gup
          when: gup_exists is failed
          ansible.builtin.shell: go install -v -ldflags="-s -w" github.com/nao1215/gup@latest
          tags:
            - go
        - name: check if gup config exists
          stat:
            path: ~/.config/gup/gup.conf
          register: stat_result
        - name: gup config found install gup (go) tools
          ansible.builtin.shell: gup import
          when: stat_result.stat.exists
        - name: gup config not found fallback to manual install
          when: not stat_result.stat.exists
          # cross platform packages
          ansible.builtin.shell: |
            go install -ldflags="-s -w" github.com/dundee/gdu/v5/cmd/gdu@latest
            go install -ldflags="-s -w" github.com/distatus/battery/cmd/battery@latest
            go install -ldflags="-s -w" github.com/muesli/duf@latest
            go install -ldflags="-s -w" github.com/schollz/croc/v9@latest
          #creates: ~/.config/gup/gup.conf
          # windows only
          # github.com/stochmal/checkpath-go
      - name: setting up dev environment
        block:
        - name: install lf, micro, nvim
          community.general.apk:
            name: lf,micro,neovim
            state: latest
          tags:
            - dev
      - name: setting up rust toolchain and rust packages
        block:
        - name: check if cargo is installed
          ansible.builtin.shell: command -v cargo
          register: cargo_exists
          ignore_errors: true
          changed_when: false
          tags:
            - rust
        - name: install build-base, rustup, sccache
          when: cargo_exists is failed
          # ansible.builtin.package:
          community.general.apk:
            name: build-base,rustup,sccache
            state: present
          tags:
            - rust
        - name: install rustup toolchain
          when: cargo_exists is failed
          ansible.builtin.shell: |
            rustup-init -y --profile minimal
            source ~/.cargo/env
            rustup default stable
          args:
            creates: ~/.cargo/bin/cargo
          tags:
            - rust
        - name: create a symbolic link for cargo in /usr/local/bin
          ansible.builtin.file:
            src: ~/.cargo/bin/cargo
            dest: /usr/local/bin/cargo
            state: link
        - name: create cargo config file
          copy:
            content: ""
            dest: ~/.cargo/config.toml
            force: false
        - name: configure cargo to use sccache
          ansible.builtin.blockinfile:
            path: ~/.cargo/config.toml
            block: |
              [build]
              rustc-wrapper = "sccache"
        - name: install cargo tools
          community.general.cargo:
            name: zoxide
            state: latest
          tags:
            - rust
